//from HodgeData in hodge.m

import "misc.m": function_field;

function infdeg(Q)

  d:=Degree(Q);
  K := BaseRing(BaseRing(Q));

  // find the points at infinity:

  Kx := RationalFunctionField(K);
  Kxy := PolynomialRing(Kx);

  FF<u> := function_field(Q); // function field of curve over K
  infplaces:=InfinitePlaces(FF);
  infplacesKinf := infplaces;
  print "These are the infinite places ", infplacesKinf;

  Kinf := K;
  repeat 
    for Kinf_new in infplacesKinf do
      if not IsOne(Degree(Kinf_new)) then
        print "This is Kinf_new", Kinf_new;
        // field generated by points at infinity
        //time norm_clos := NormalClosure(AbsoluteField(ResidueClassField(Kinf_new)));
        //time Kinf := Compositum(Kinf, norm_clos);
        time split := SplittingField(CharacteristicPolynomial(ResidueClassField(Kinf_new).1));
        time Kinf<s> := Compositum(Kinf, split);
        print "This is Kinf", Kinf;
      end if;
    end for;

    Kinfx<t>:=RationalFunctionField(Kinf);
    Kinfxy<v>:=PolynomialRing(Kinfx);
    FFKinf:=FunctionField(Kinfxy!Q); // function field of curve over Kinf

    time print "This is the function field of Q\n", FFKinf;

    time infplacesKinf:=InfinitePlaces(FFKinf); // places at infinity all of degree 1, will be denoted by P
  until &and[IsOne(Degree(P)) : P in infplacesKinf];
  return Kinf, AbsoluteDegree(Kinf), FFKinf;
end function;

K<u> := CyclotomicField(3);
Kx<x> := PolynomialRing(K);
Kxy<y> := PolynomialRing(Kx);

L := [
y^4 + ((-7*u + 11)*x + (2*u + 3))*y^3 + (-3*x^2 + 6*x - 3)*y^2 + ((-1413*u - 398)*x^3 + (-591*u - 123)*x^2 + (-108*u - 15)*x - 10*u - 2)*y + (-10*u + 491)*x^4 + (-184*u - 231)*x^3 + (135*u - 219)*x^2 + (53*u - 41)*x + 6*u,
y^4 + ((-2*u + 9)*x + (2*u + 3))*y^3 + (-3*x^2 + 6*x - 3)*y^2 + ((-170*u + 254)*x^3 + (-150*u + 114)*x^2 + (-54*u + 18)*x - 10*u - 2)*y + (162*u + 144)*x^4 + (-108*u + 48)*x^3 + (-72*u - 144)*x^2 + (12*u - 48)*x + 6*u,
y^4 + ((16*u + 12)*x + (2*u + 3))*y^3 + (-3*x^2 + 6*x - 3)*y^2 + ((-683*u - 1924)*x^3 + (738*u + 45)*x^2 + (69*u + 147)*x - 10*u - 2)*y + (-1212*u - 612)*x^4 + (1464*u + 186)*x^3 + (-153*u + 540)*x^2 + (-105*u - 114)*x + 6*u,
y^4 + ((21*u + 10)*x + (2*u + 3))*y^3 + (-3*x^2 + 6*x - 3)*y^2 + ((-3418*u - 2988)*x^3 + (711*u - 576)*x^2 + (123*u + 180)*x - 10*u - 2)*y + (-1703*u + 445)*x^4 + (1579*u - 1407)*x^3 + (264*u + 1083)*x^2 + (-146*u - 121)*x + 6*u
];

Q1:=Polynomial([PolynomialRing(CyclotomicField(3)) | [[ RationalField() | 0, 6 ], [ RationalField() | -12, -9 ], [ RationalField() | 9, 0 ], [ RationalField() | -3, 6 ], [ RationalField() | -3, -3 ]], [[ RationalField() | 2, 10 ], [ RationalField() | -21, -15 ], [ RationalField() | 9, 0 ], [ RationalField() | -2, -1 ]], [[ RationalField() | -3, 0 ], [ RationalField() | -6, -6 ], [ RationalField() | 0, -3 ]], [[ RationalField() | -3, -2 ], [ RationalField() | 2, -3 ]], [[ RationalField() | 1, 0 ]]]);
Q := Polynomial([PolynomialRing(CyclotomicField(3)) | [[ RationalField() | 1, 1 ], [ RationalField() | 1, -1 ], [ RationalField() | 0, 3 ], [ RationalField() | 0, -1 ]], [[ RationalField() | 0, -2 ], [ RationalField() | 0, 3 ], [ RationalField() | 0, -3 ], [ RationalField() | 2, 2 ]], [[ RationalField() | -3, 0 ]], [[ RationalField() | 2, 3 ], [ RationalField() | -1, 1 ]], [[ RationalField() | 1, 0 ]]]);
FF,deg,FFx:=infdeg(Q);
